#! configuration/base.yaml
application:
  port: 8000
  host: 127.0.0.1
  # You need to set the `APP_APPLICATION__HMAC_SECRET` environment variable
  # on Digital Ocean as well for production!
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "127.0.0.1"
  # Use the single sender email you authorised on Postmark!
  sender_email: "test@gmail.com"
  # We are only setting the development value,
  # we'll deal with the production token outside of version control
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
# 6379 is Redis' default port
redis_uri: "redis://127.0.0.1:6379"
